
# rules are applied
opt_in_rules:
    - force_unwrapping
    - control_statement
    - empty_count
    - trailing_newline
    - colon
    - comma

# force unwrapping warning
force_unwrapping: warning

# disable rules
disabled_rules:
    - line_length
    - force_cast
    - trailing_whitespace
    - colon
    - mark
    - type_name
    - legacy_constructor

# todo warnings
todo: warning

# force case warnings
force_cast: warning
force_try:
  severity: warning

# function body control
function_body_length:
  warning: 50
  error: 60
line_length: 120

# identifier name rules
identifier_name:
    min_length:
        error: 3
    excluded:
        - db
        - id
    allowed_symbols: "_"

reporter: "xcode"
